kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: hadolint/hadolint:v1.18.0
    commands:
      - hadolint ubuntu_build-20.04/Dockerfile
      - hadolint openssl_build-1.1.1g/Dockerfile
      - hadolint squid_build-5.0.3/Dockerfile
      - hadolint squid_build-latest/Dockerfile
      - hadolint squid-5.0.3/Dockerfile      
      - hadolint squid-latest/Dockerfile      

  - name: ubuntu_build-20.04
    image: plugins/docker
    settings:
      dockerfile: ubuntu_build-20.04/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/squid_docker
      tags:
        - ubuntu_build-20.04

  - name: openssl_build-1.1.1g
    image: plugins/docker
    depends_on:
      - ubuntu_build-20.04
    settings:
      dockerfile: openssl_build-1.1.1g/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/squid_docker
      tags:
        - openssl_build-1.1.1g

  - name: squid_build-5.0.3
    image: plugins/docker
    depends_on:
      - openssl_build-1.1.1g
    settings:
      dockerfile: squid_build-5.0.3/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/squid_docker
      tags:
        - squid_build-5.0.3

  - name: squid_build-latest
    image: plugins/docker
    depends_on:
      - openssl_build-1.1.1g
    settings:
      dockerfile: squid_build-latest/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/squid_docker
      tags:
        - squid_build-latest

  - name: squid-5.0.3
    image: plugins/docker
    depends_on:
      - openssl_build-1.1.1g
      - squid_build-5.0.3
    settings:
      dockerfile: squid-5.0.3/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/squid_docker
      tags:
        - squid-5.0.3

  - name: squid-latest
    image: plugins/docker
    depends_on:
      - openssl_build-1.1.1g
      - squid_build-latest
    settings:
      dockerfile: squid-latest/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/squid_docker
      tags:
        - latest
