kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_docker
      tags:
        - latest
        - 4.11
